---
"dictionary/{term}":
  _template: dictentry.html
  word:
    _sql: SELECT * FROM words where word = :term
    _single: 'true'
blog/:
  _template: blog.html
  posts:
    _sql: "
      SELECT
        posts.title,
        substr(posts.body, 0, 500) AS body,
        posts.postdate,
        CONCAT('p', posts.id, '.html') AS link,
        people.name,
        CONCAT('../people/p', people.id,'.html') AS authorlink
      FROM posts
      NATURAL JOIN postauthors
      NATURAL JOIN people
      ORDER BY posts.id,
      postauthors.percent,
      people.name "
    authors:
    - name
    - authorlink
  menusections: &menusections
    _sql: "
      SELECT
        link.url,
        link.text,
        menu.title
      FROM links
      NATURAL JOIN menus
      ORDER BY menu.section, menu.menu_order, link.link_order "
    menus:
    - title
    links:
    - url
    - text
"blog/p{postid}.html":
  _template: post.html
  post:
    _sql: "
      SELECT
        posts.title,
        posts.body,
        posts.postdate, CONCAT('p', posts.id,'.html') AS link,
        people.name,
        CONCAT('../people/p', people.id, '.html') AS authorlink
      FROM posts
      NATURAL JOIN postauthors
      NATURAL JOIN people
      WHERE posts.id = :postid
      ORDER BY postauthors.percent, people.name "
    _single: 'true'
    authors:
    - name
    - authorlink
  comments:
    _sql: "
      SELECT
        comments.text,
        comments.commentdate,
        people.name,
        CONCAT('../people/p', people.id, '.html') AS commenterlink
      FROM comments
      NATURAL JOIN people
      WHERE comments.postid = :postid
      ORDER BY commentdate "
    commenter:
    - name
    - commenterlink
  menusections:
		<<: *menusections

